AWSTemplateFormatVersion: "2010-09-09"
Description: "Clase 3 - System Manager: 2 instancias Linux con SSM y S3 Full Access (solo AZ 1a y 1b)"

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::marcos-usash-key
    Description: "Nombre del KeyPair existente"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC donde crear las instancias"

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet donde crear las instancias (debe estar en la AZ seleccionada)"

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small

  AvailabilityZone:
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
    Description: "Zona de disponibilidad permitida"

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
    Description: "Amazon Linux 2023 más reciente vía SSM"

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG para laboratorio System Manager"
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  SsmEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Clase3-SSM-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: Clase3-SSM-InstanceProfile
      Roles:
        - !Ref SsmEc2Role

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref SsmInstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: SM-Linux-01
        - Key: Platform
          Value: LINUX

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref SsmInstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: SM-Linux-02
        - Key: Platform
          Value: LINUX

Outputs:
  Instance1Id:
    Description: "ID de la primera instancia"
    Value: !Ref EC2Instance1

  Instance2Id:
    Description: "ID de la segunda instancia"
    Value: !Ref EC2Instance2

  RoleName:
    Description: "Rol IAM asociado a las instancias"
    Value: !Ref SsmEc2Role
